[loggers]
keys=root,demologger1

[handlers]
keys=consoleHandler

[formatters]
keys=sampleFormatter


[logger_root]
level=DEBUG
handlers=consoleHandler


[logger_demologger1]
level=DEBUG
handlers=consoleHandler
qualname=demoLogger1

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=sampleFormatter
args=(sys.stdout,)

[formatter_sampleFormatter]
format=%(asctime)s:%(created)f:%(levelname)s:%(name)s:%(message)s
datefmt=%d:%m:%Y %I:%M:%S %p